apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-1
spec:
  to:
    kind: Service
    name: service-1
  port:
    targetPort: 8081
  tls:
    termination: edge
  wildcardPolicy: None
 
